subcomponents:
  hello-rings-featurea:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurea-4066
  hello-rings-featureb:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featureb-4067
  hello-rings-featurec:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurec-4068
  hello-rings-featured:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featured-4069
  hello-rings-featuree:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featuree-4082
  hello-rings-featuref:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featuref-4093
  hello-rings-master:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-master-4132
