subcomponents:
  hello-rings-featurea:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurea-4020
  hello-rings-featureb:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featureb-4021
  hello-rings-featurec:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurec-3975
  hello-rings-master:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-master-4019
